# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
desc "Runs app's unit tests in the specified device."
desc "Usage example: fastlane unit_test device:'iPhone 8' ios_version:'12.4'"
lane :unit_test do 
	scan(
	    scheme: "RecipePuppyTests",
	    clean: true,
	    disable_concurrent_testing: true
  	)
end
end
